[pytest]
addopts = -v --tb=short
testpaths = tests
python_files = test_*.py
log_cli = true
log_cli_level = INFO
log_file = reports/logs/pytest_live.log
log_file_level = DEBUG
filterwarnings = ignore::DeprecationWarning