[settings]
base_url = https://www.saucedemo.com
browser = chrome

[timeouts]
timeout = 10
implicit_wait = 0
explicit_wait = 10
page_load_wait = 15
# the credentials are included because they are public
[credentials]
standard_user = standard_user
locked_user = locked_out_user
problem_user = problem_user
password = secret_sauce

[paths]
screenshot_dir = reports/screenshots
log_dir = reports/logs
report_dir = reports

[logging]
log_level = DEBUG
log_format = %(asctime)s  [%(levelname)-8s]  %(name)s  →  %(message)s 
log_datefmt= %Y-%m-%d %H:%M:%S

[data]
json_file = test_data/login_data.json
json_file_e2e = test_data/checkout_data.json